org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1

minecraft_version_range=[1.20.1]
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
version_ie=1.20.1-10.1.0-171
jei_version=15.20.0.132

mod_id=immersivefarming
mod_name=Immersive Farming UNOFFICIAL
mod_license=MIT
mod_version=0.4
mod_group_id=net.etylop.immersivefarming
mod_authors=Etyl, Xg787
mod_description=Addon for Immersive Engineering focusing on improving the farming experience.